name: CI
on: 
  push:
    branches: 
    - 'WORKING_BLOG_BRANCH'  
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      # - name: Update theme
      #   # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
      #   run: git submodule update --init --recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          hugo-version: '0.85.0'
          extended: true

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.BLOG }}
          publish_dir: ./docs
          allow_empty_commit: true
          #  keep_files: true
          user_name: carnellj
          user_email: john_carnell@yahoo.com
          publish_branch: main
          cname: thoughtmechanix.com
